{
	"version": 1747608635,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/homebackground.png",
		"images/logo.png",
		"images/startbackground.png",
		"images/banditicon-sheet0.png",
		"images/banditsprite-sheet0.png",
		"images/banditsprite-sheet1.png",
		"images/mageicon-sheet0.png",
		"images/magesprite-sheet0.png",
		"images/knighticon-sheet0.png",
		"images/knightsprite-sheet0.png",
		"images/zone1background.png",
		"images/limitdown-sheet0.png",
		"images/scorpion-sheet0.png",
		"images/banditpistolbullet-sheet0.png",
		"images/knightaxebullet-sheet0.png",
		"images/sprite-sheet0.png",
		"images/gameoverbackground.png",
		"images/levelupbackground.png",
		"media/track 02 main theme.m4a",
		"media/track 02 main theme.ogg",
		"media/zone 1 vordt of the boreal valley.m4a",
		"media/zone 1 vordt of the boreal valley.ogg",
		"media/banditgun.m4a",
		"media/banditgun.ogg",
		"media/knightgun.m4a",
		"media/knightgun.ogg",
		"media/levelup_final.m4a",
		"media/levelup_final.ogg",
		"media/magegun.m4a",
		"media/magegun.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}